Repository skbkontur/retail-ui, pull requests merged in 2019-03, with the labels that each got.

#1218 fix(Tooltip): fix svg icons click in ie11
  packages/retail-ui/lib/listenFocusOutside.tsx
Labels: bug

#1226 fix(ComboBoxMenu): unique keys warning
  packages/retail-ui/components/CustomComboBox/ComboBoxMenu.tsx
Labels: bug

#1230 docs(LocaleProvider): refactor example
  packages/retail-ui/LOCALEPROVIDER.md
Labels: bug, docs

#1233 refactor(retail-ui-locale): refactor interfaces
  packages/retail-ui/components/CustomComboBox/ComboBoxMenu.tsx
  packages/retail-ui/components/CustomComboBox/locale/types.ts
  packages/retail-ui/components/LocaleProvider/decorators.tsx
  packages/retail-ui/components/LocaleProvider/types.ts
  packages/retail-ui/components/Logotype/Logotype.tsx
  packages/retail-ui/components/Logotype/locale/types.ts
  packages/retail-ui/components/Paging/Paging.tsx
  packages/retail-ui/components/Paging/locale/types.ts
  packages/retail-ui/components/Select/Select.tsx
  packages/retail-ui/components/Select/locale/types.ts
  packages/retail-ui/components/Spinner/Spinner.tsx
  packages/retail-ui/components/Spinner/locale/types.ts
  packages/retail-ui/components/TokenInput/TokenInputMenu.tsx
  packages/retail-ui/components/TokenInput/locale/types.ts
  packages/retail-ui/components/TopBar/TopBarLogout.tsx
  packages/retail-ui/components/TopBar/User.tsx
  packages/retail-ui/components/TopBar/locale/types.ts
Labels: enhancement

#1266 fix(hint): add pin offset
  packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/ie11.png
  packages/retail-ui/components/Hint/Hint.tsx
Labels: bug
