Repository skbkontur/retail-ui, pull requests merged in 2019-07, with the labels that each got.

#1494 fix(Textarea): add blocking Enter after reaching 'maxLength'
  packages/retail-ui/components/Textarea/Textarea.tsx
Labels: bug

#1496 fix(Input): add calling 'selectAll' via 'setTimeout'
  packages/retail-ui/components/Input/Input.tsx
Labels: bug

#1274 docs: change contributing.md
  contributing.md
Labels: docs

#1509 [LTS] fix(Textarea): add blocking Enter after reaching 'maxLength'
  packages/retail-ui/components/Textarea/Textarea.tsx
Labels: LTS, bug, duplicate

#1508 [LTS] fix(Input): add calling 'selectAll' via 'raf'
  packages/retail-ui/components/Input/Input.tsx
Labels: LTS, bug, duplicate

#1511 feat(Switcher): add prop 'size'
  packages/retail-ui/components/Switcher/Switcher.tsx
Labels: enhancement

#1516 chore(Textarea): remove backlit spell checker
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by prop/Focused/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by prop/Focused/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by prop/Focused/firefoxFlat.png
  packages/retail-ui/components/Textarea/__stories__/textarea.stories.tsx
Labels: technical debt

#1513 fix(Button): change 'background-color' and 'border-color' when hovering
  packages/react-ui-screenshot-tests/gemini/screens/Input set selection/Select all by button/Selected/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input set selection/Select all by button/Selected/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input set selection/Select all by button/Selected/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Textarea/Selection/Select all by button/Selected/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/clicked/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/clicked/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/clicked/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/hover/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/hover/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/hover/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/pressed/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/pressed/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/button/button/pressed/ie11Flat.png
  packages/retail-ui/components/Button/Button.styles.ts
  packages/retail-ui/components/variables.flat.less
Labels: bug

#1507 [LTS] fix(Input): delete CSS class '.focus' for flat theme
  packages/react-ui-screenshot-tests/gemini/input.js
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/ie11.png
  packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/ie11.png
  packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/ie11Flat.png
  packages/retail-ui/components/Input/Input.flat.less
  packages/retail-ui/components/Input/__stories__/Input.stories.tsx
Labels: LTS, bug
