Repository skbkontur/retail-ui, pull requests merged in 2019-08, with the labels that each got.

#1536 test(Radio): change story to correct focus using key 'tab'
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/ie11.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/plain/ie11Flat.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/chromeFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/firefoxFlat.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/ie11.png
  packages/react-ui-screenshot-tests/gemini/screens/Radio highlighted/tabPress/ie11Flat.png
  packages/retail-ui/components/Radio/__stories__/Radio.stories.tsx
Labels: technical debt

#1540 fix(Radio): fix long typechecking
  packages/retail-ui/components/Radio/Radio.tsx
Labels: LTS

#1554 build(react-ui-testing): update deps
  packages/react-ui-testing/PromoSite/package.json
  packages/react-ui-testing/PromoSite/yarn.lock
Labels: dependencies

#1567 refactor(Button): mixins
  packages/retail-ui/components/Button/Button.mixins.ts
  packages/retail-ui/components/Button/Button.styles.ts
  packages/retail-ui/components/Button/Button.tsx
  packages/retail-ui/components/variables.less
  packages/retail-ui/lib/theming/themes/DefaultTheme.ts
Labels: enhancement
