Repository skbkontur/retail-ui, pull requests merged in 2019-06, with the labels that each got.

#1452 fix(MaskedInput): add support prop 'defaultValue'
  packages/retail-ui/components/internal/MaskedInput/MaskedInput.tsx
  packages/retail-ui/components/internal/MaskedInput/__tests__/MaskedInput-test.tsx
Labels: bug

#1445 Token input disabled state
  packages/react-ui-screenshot-tests/gemini/Token.js
  packages/react-ui-screenshot-tests/gemini/screens/Token/disabled/idle/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/Token/disabled/idle/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/Token/disabled/idle/ie11.png
  packages/react-ui-screenshot-tests/gemini/screens/TokenInput/disabled/idle/chrome.png
  packages/react-ui-screenshot-tests/gemini/screens/TokenInput/disabled/idle/firefox.png
  packages/react-ui-screenshot-tests/gemini/screens/TokenInput/disabled/idle/ie11.png
  packages/react-ui-screenshot-tests/gemini/tokenInput.js
  packages/retail-ui/components/Token/Colors.less
  packages/retail-ui/components/Token/Token.less
  packages/retail-ui/components/Token/Token.tsx
  packages/retail-ui/components/Token/__stories__/Token.stories.tsx
  packages/retail-ui/components/TokenInput/TokenInput.less
  packages/retail-ui/components/TokenInput/TokenInput.tsx
  packages/retail-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
  packages/retail-ui/components/variables.less
Labels: bug

#1459 feat(Fias): add localization
  packages/retail-ui/LOCALEPROVIDER.md
  packages/retail-ui/components/Fias/Fias.js.flow
  packages/retail-ui/components/Fias/Fias.tsx
  packages/retail-ui/components/Fias/FiasModal.js.flow
  packages/retail-ui/components/Fias/FiasModal.tsx
  packages/retail-ui/components/Fias/Form/FiasCountrySelector.tsx
  packages/retail-ui/components/Fias/Form/FiasForm.js.flow
  packages/retail-ui/components/Fias/Form/FiasForm.tsx
  packages/retail-ui/components/Fias/Form/FiasSearch.js.flow
  packages/retail-ui/components/Fias/Form/FiasSearch.tsx
  packages/retail-ui/components/Fias/README.md
  packages/retail-ui/components/Fias/__stories__/Fias.stories.tsx
  packages/retail-ui/components/Fias/locale/index.ts
  packages/retail-ui/components/Fias/locale/locales/ru.ts
  packages/retail-ui/components/Fias/locale/types.js.flow
  packages/retail-ui/components/Fias/locale/types.ts
  packages/retail-ui/components/Fias/models/Address.ts
  packages/retail-ui/components/Fias/models/__tests__/Address/Address-test.ts
  packages/retail-ui/components/Fias/models/__tests__/Address/__fixtures__/validation.ts
  packages/retail-ui/components/Fias/types.js.flow
  packages/retail-ui/components/Fias/types.ts
  packages/retail-ui/components/LocaleProvider/LocaleHelper.ts
  packages/retail-ui/components/LocaleProvider/types.ts
Labels: enhancement, localization

#1474 fix(DateInputFallback): remove unnecessary call 'emitChange'
  packages/retail-ui/components/DateInput/DateInputFallback.tsx
Labels: bug

#1472 fix(DropdownContainer): change calculations for positioning up
  packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx
Labels: bug

#1468 fix(CurrencyInput): add 15-digit limit and warning about it
  packages/retail-ui/components/CurrencyInput/CurrencyHelper.tsx
  packages/retail-ui/components/CurrencyInput/CurrencyInput.tsx
  packages/retail-ui/components/CurrencyInput/README.md
  packages/retail-ui/components/CurrencyInput/__tests__/CurrencyHelper-test.tsx
  packages/retail-ui/components/CurrencyInput/constants.ts
  packages/retail-ui/components/CurrencyLabel/CurrencyLabel.tsx
Labels: docs, technical debt
