Repository skbkontur/retail-ui, pull requests merged in 2020-08, with the labels that each got.

#2077 fix(Kladr): add filter for "empty" addresses from backend (3)
  packages/retail-ui/components/Kladr/KladrAPI.js
Labels: duplicate

#2086 chore(react-ui-testing): update deps by dependabot
  packages/react-ui-testing/PromoSite/yarn.lock
  packages/react-ui-testing/TestPages/yarn.lock
Labels: dependencies

#2109 fix(MenuItem): pass state into custom component
  packages/retail-ui/components/MenuItem/MenuItem.tsx
Labels: LTS
